export const AUDIT_ENTITY = {
  CONTEXT_READING: 'ContextReading',
  WORK: 'Work',
  SERIES: 'Series',
  CHARACTER: 'Character',
  WORLD: 'World',
  PLACE: 'Place',
} as const;

export const AUDIT_ACTION = {
  CONTEXT_UPDATE: 'CONTEXT_UPDATE',
  CONTEXT_UNPUBLISH: 'CONTEXT_UNPUBLISH',
  CONTEXT_REJECT: 'CONTEXT_REJECT',
  WORK_PUBLISH: 'WORK_PUBLISH',
  WORK_SOFT_DELETE: 'WORK_SOFT_DELETE',
  WORK_MERGE: 'WORK_MERGE',
  CATALOG_IMPORT_START: 'CATALOG_IMPORT_START',
  SERIES_PUBLISH: 'SERIES_PUBLISH',
  SERIES_SOFT_DELETE: 'SERIES_SOFT_DELETE',
  CHARACTER_PUBLISH: 'CHARACTER_PUBLISH',
  CHARACTER_SOFT_DELETE: 'CHARACTER_SOFT_DELETE',
  WORLD_PUBLISH: 'WORLD_PUBLISH',
  WORLD_SOFT_DELETE: 'WORLD_SOFT_DELETE',
  PLACE_PUBLISH: 'PLACE_PUBLISH',
  PLACE_SOFT_DELETE: 'PLACE_SOFT_DELETE',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
