export const AUDIT_ENTITY = {
  CONTEXT_READING: 'ContextReading',
  WORK: 'Work',
} as const;

export const AUDIT_ACTION = {
  CONTEXT_UPDATE: 'CONTEXT_UPDATE',
  CONTEXT_UNPUBLISH: 'CONTEXT_UNPUBLISH',
  CONTEXT_REJECT: 'CONTEXT_REJECT',
  WORK_PUBLISH: 'WORK_PUBLISH',
  WORK_SOFT_DELETE: 'WORK_SOFT_DELETE',
  WORK_MERGE: 'WORK_MERGE',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
